#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"; PYTHON="${PYTHON:-python3}"; METHOD="${METHOD:-all}"
METADATA="${METADATA:?Set METADATA}"; OUTPUT_ROOT="${OUTPUT_ROOT:-$ROOT/outputs/infer}"; CUDA_VISIBLE_GPU="${CUDA_VISIBLE_GPU:-0}"
START_INDEX="${START_INDEX:-0}"; MAX_SAMPLES="${MAX_SAMPLES:--1}"; OVERWRITE="${OVERWRITE:-0}"; SEED="${SEED:-17}"; STRICT="${STRICT:-0}"
SAMPLING_STEPS="${SAMPLING_STEPS:-2000}"; ZMFF_ITERATIONS="${ZMFF_ITERATIONS:-1300}"; REDIFFUSE_PYTHON="${REDIFFUSE_PYTHON:-python3.8}"
SWINFUSION_CHECKPOINT_MODE="${SWINFUSION_CHECKPOINT_MODE:-official-y}"
REDIFFUSE_CHECKPOINT_MODE="${REDIFFUSE_CHECKPOINT_MODE:-official-y}"
[[ -f "$METADATA" ]] || { echo '[ERROR] metadata missing' >&2; exit 2; }; mkdir -p "$OUTPUT_ROOT"; failed=0
export CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_GPU"
echo "[GPU] CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES (Python device cuda:0)"
skip() { [[ "$STRICT" != 1 && "${METHOD,,}" == all ]] && { echo "[SKIP] $1"; return 0; }; echo "[ERROR] $1" >&2; return 3; }
run_ifcnn(){ local c="${IFCNN_CKPT:-}"; [[ -f "$c" ]]||{ skip 'IFCNN_CKPT missing'; return; }; "$PYTHON" "$ROOT/baselines/IFCNN/infer_metadata.py" --metadata "$METADATA" --output-dir "$OUTPUT_ROOT/IFCNN" --checkpoint "$c" --start-index "$START_INDEX" --max-samples "$MAX_SAMPLES" --overwrite "$OVERWRITE"; }
run_swin(){ local c="${SWINFUSION_CKPT:-}" out="$OUTPUT_ROOT/SwinFusion-$SWINFUSION_CHECKPOINT_MODE"; [[ -f "$c" ]]||{ skip 'SWINFUSION_CKPT missing'; return; }; echo "[RUN] method=swinfusion checkpoint=$c checkpoint_mode=$SWINFUSION_CHECKPOINT_MODE seed=$SEED metadata=$METADATA output_dir=$out device=cuda:0"; "$PYTHON" "$ROOT/baselines/SwinFusion/infer_metadata.py" --metadata "$METADATA" --output-dir "$out" --checkpoint "$c" --checkpoint-mode "$SWINFUSION_CHECKPOINT_MODE" --device cuda:0 --start-index "$START_INDEX" --max-samples "$MAX_SAMPLES" --overwrite "$OVERWRITE"; }
run_fd(){ local c="${FUSIONDIFF_CKPT:-}"; [[ -f "$c" ]]||{ skip 'FUSIONDIFF_CKPT missing'; return; }; local stem="$(basename "$c")"; local out="$OUTPUT_ROOT/FusionDiff-${stem%.*}"; echo "[RUN] method=fusiondiff checkpoint=$c checkpoint_mode=metadata-rgb seed=$SEED metadata=$METADATA output_dir=$out device=cuda:0 sampling_steps=$SAMPLING_STEPS"; "$PYTHON" "$ROOT/baselines/ImageFusion/FusionDiff/infer_metadata.py" --metadata "$METADATA" --output-dir "$out" --checkpoint "$c" --device cuda:0 --seed "$SEED" --sampling-steps "$SAMPLING_STEPS" --start-index "$START_INDEX" --max-samples "$MAX_SAMPLES" --overwrite "$OVERWRITE"; }
run_rd(){ local c="${REDIFFUSE_CKPT:-$ROOT/baselines/ReDiffuse/weights/model.pt}" out="$OUTPUT_ROOT/ReDiffuse-$REDIFFUSE_CHECKPOINT_MODE"; [[ -f "$c" ]]||{ skip 'REDIFFUSE_CKPT missing'; return; }; echo "[RUN] method=rediffuse checkpoint=$c checkpoint_mode=$REDIFFUSE_CHECKPOINT_MODE seed=$SEED metadata=$METADATA output_dir=$out device=cuda:0 sampling_steps=$SAMPLING_STEPS"; "$REDIFFUSE_PYTHON" "$ROOT/baselines/ReDiffuse/prepare_official_bytecode.py"; "$REDIFFUSE_PYTHON" "$ROOT/baselines/ReDiffuse/infer_metadata.py" --metadata "$METADATA" --output-dir "$out" --checkpoint "$c" --checkpoint-mode "$REDIFFUSE_CHECKPOINT_MODE" --device cuda:0 --seed "$SEED" --sampling-steps "$SAMPLING_STEPS" --start-index "$START_INDEX" --max-samples "$MAX_SAMPLES" --overwrite "$OVERWRITE"; }
run_zmff(){ "$PYTHON" "$ROOT/baselines/ZMFF/infer_metadata.py" --metadata "$METADATA" --output-dir "$OUTPUT_ROOT/ZMFF" --iterations "$ZMFF_ITERATIONS" --max-optimize-side "${ZMFF_MAX_SIDE:-1024}" --seed "$SEED" --start-index "$START_INDEX" --max-samples "$MAX_SAMPLES" --overwrite "$OVERWRITE"; }
run_dsift(){ "$PYTHON" "$ROOT/baselines/DSIFT-MFIF/infer_metadata.py" --metadata "$METADATA" --output-dir "$OUTPUT_ROOT/DSIFT" --start-index "$START_INDEX" --max-samples "$MAX_SAMPLES" --overwrite "$OVERWRITE" --device "${DSIFT_DEVICE:-auto}" --chunk-rows "${DSIFT_CHUNK_ROWS:-0}" --scale "${DSIFT_SCALE:-48}" --block-size "${DSIFT_BLOCK_SIZE:-8}" --matching "${DSIFT_MATCHING:-1}"; }
one(){ case "$1" in dsift)run_dsift;;ifcnn)run_ifcnn;;swinfusion)run_swin;;zmff)run_zmff;;fusiondiff)run_fd;;rediffuse)run_rd;;esac; }
if [[ "${METHOD,,}" == all ]]; then for m in dsift ifcnn swinfusion zmff fusiondiff rediffuse; do one "$m"||failed=$((failed+1)); done; else one "${METHOD,,}"; fi
echo "[DONE] failed=$failed"; [[ "$failed" == 0 ]]
