#!/usr/bin/env bash
set -Eeuo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

METHOD_NAME="FusionDiff"
TAG="${TAG:-fusiondiff_metadata_rgb_v1}"
TRAIN_META="${TRAIN_META:-}"
VAL_META="${VAL_META:-}"
TEST_META="${TEST_META:-}"
TRAIN_OUTPUT="$OUTPUT_ROOT/train/$METHOD_NAME/$TAG"
INFER_OUTPUT="$OUTPUT_ROOT/infer"
EVAL_OUTPUT="$OUTPUT_ROOT/eval/$METHOD_NAME/$TAG"
FUSIONDIFF_CKPT="${FUSIONDIFF_CKPT:-$TRAIN_OUTPUT/best_val_loss.pt}"
INIT_CHECKPOINT="${INIT_CHECKPOINT:-}"
RESUME="${RESUME:-}"
NUM_WORKERS="${NUM_WORKERS:-4}"
MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-20000}"
VALIDATION_MODE="${VALIDATION_MODE:-loss}"

if [[ "$RUN_TRAIN" == 1 ]]; then
  require_file "$TRAIN_META" TRAIN_META
  require_file "$VAL_META" VAL_META
  METHOD=fusiondiff TRAIN_META="$TRAIN_META" VAL_META="$VAL_META" OUTPUT_ROOT="$OUTPUT_ROOT/train" \
    TAG="$TAG" GPUS="$CUDA_VISIBLE_GPU" PYTHON="$PYTHON" INIT_CHECKPOINT="$INIT_CHECKPOINT" \
    RESUME="$RESUME" NUM_WORKERS="$NUM_WORKERS" MAX_SAMPLES="$MAX_SAMPLES" \
    MAX_TRAIN_STEPS="$MAX_TRAIN_STEPS" SEED="$SEED" VALIDATION_MODE="$VALIDATION_MODE" \
    bash "$ROOT/run_train_metadata_v3.sh"
fi

if [[ "$RUN_INFER" == 1 ]]; then
  require_file "$TEST_META" TEST_META
  require_file "$FUSIONDIFF_CKPT" FUSIONDIFF_CKPT
  METHOD=fusiondiff METADATA="$TEST_META" OUTPUT_ROOT="$INFER_OUTPUT" PYTHON="$PYTHON" \
    FUSIONDIFF_CKPT="$FUSIONDIFF_CKPT" CUDA_VISIBLE_GPU="$CUDA_VISIBLE_GPU" SEED="$SEED" \
    SAMPLING_STEPS="$SAMPLING_STEPS" START_INDEX="$START_INDEX" MAX_SAMPLES="$MAX_SAMPLES" \
    OVERWRITE="$OVERWRITE" bash "$ROOT/run_infer_metadata_v3.sh"
fi

if [[ "$RUN_EVAL" == 1 ]]; then
  stem="$(basename "$FUSIONDIFF_CKPT")"
  export EVAL_SPECS="${EVAL_SPECS//__FUSIONDIFF_OUT__/FusionDiff-${stem%.*}}"
  run_eval_for_specs "$METHOD_NAME" "$INFER_OUTPUT" "$EVAL_OUTPUT" "$EVAL_SPECS"
fi
