#!/usr/bin/env bash
set -Eeuo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

METHOD_NAME="ReDiffuse"
TAG="${TAG:-rediffuse_metadata_rgb_v1}"
TRAIN_META="${TRAIN_META:-}"
VAL_META="${VAL_META:-}"
TEST_META="${TEST_META:-}"
TRAIN_OUTPUT="$OUTPUT_ROOT/train/$METHOD_NAME/$TAG"
INFER_OUTPUT="$OUTPUT_ROOT/infer"
EVAL_OUTPUT="$OUTPUT_ROOT/eval/$METHOD_NAME/$TAG"
REDIFFUSE_PYTHON="${REDIFFUSE_PYTHON:-python3.8}"
REDIFFUSE_CKPT="${REDIFFUSE_CKPT:-$TRAIN_OUTPUT/best_val_loss.pt}"
REDIFFUSE_CHECKPOINT_MODE="${REDIFFUSE_CHECKPOINT_MODE:-metadata-rgb}"
REDIFFUSE_MODEL_MODE="${REDIFFUSE_MODEL_MODE:-metadata-rgb}"
INIT_CHECKPOINT="${INIT_CHECKPOINT:-}"
RESUME="${RESUME:-}"
NUM_WORKERS="${NUM_WORKERS:-4}"
MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:--1}"
VALIDATION_MODE="${VALIDATION_MODE:-loss}"

if [[ "$RUN_TRAIN" == 1 ]]; then
  require_file "$TRAIN_META" TRAIN_META
  require_file "$VAL_META" VAL_META
  METHOD=rediffuse TRAIN_META="$TRAIN_META" VAL_META="$VAL_META" OUTPUT_ROOT="$OUTPUT_ROOT/train" \
    TAG="$TAG" GPUS="$CUDA_VISIBLE_GPU" PYTHON="$PYTHON" REDIFFUSE_PYTHON="$REDIFFUSE_PYTHON" \
    REDIFFUSE_MODEL_MODE="$REDIFFUSE_MODEL_MODE" INIT_CHECKPOINT="$INIT_CHECKPOINT" RESUME="$RESUME" \
    NUM_WORKERS="$NUM_WORKERS" MAX_SAMPLES="$MAX_SAMPLES" MAX_TRAIN_STEPS="$MAX_TRAIN_STEPS" \
    SEED="$SEED" VALIDATION_MODE="$VALIDATION_MODE" bash "$ROOT/run_train_metadata_v3.sh"
fi

if [[ "$RUN_INFER" == 1 ]]; then
  require_file "$TEST_META" TEST_META
  require_file "$REDIFFUSE_CKPT" REDIFFUSE_CKPT
  METHOD=rediffuse METADATA="$TEST_META" OUTPUT_ROOT="$INFER_OUTPUT" PYTHON="$PYTHON" \
    REDIFFUSE_PYTHON="$REDIFFUSE_PYTHON" REDIFFUSE_CKPT="$REDIFFUSE_CKPT" \
    REDIFFUSE_CHECKPOINT_MODE="$REDIFFUSE_CHECKPOINT_MODE" CUDA_VISIBLE_GPU="$CUDA_VISIBLE_GPU" \
    SEED="$SEED" SAMPLING_STEPS="$SAMPLING_STEPS" START_INDEX="$START_INDEX" \
    MAX_SAMPLES="$MAX_SAMPLES" OVERWRITE="$OVERWRITE" bash "$ROOT/run_infer_metadata_v3.sh"
fi

if [[ "$RUN_EVAL" == 1 ]]; then
  export EVAL_SPECS="${EVAL_SPECS//__REDIFFUSE_OUT__/ReDiffuse-$REDIFFUSE_CHECKPOINT_MODE}"
  run_eval_for_specs "$METHOD_NAME" "$INFER_OUTPUT" "$EVAL_OUTPUT" "$EVAL_SPECS"
fi
