#!/usr/bin/env bash
set -Eeuo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

METHOD_NAME="SwinFusion"
TAG="${TAG:-swinfusion_metadata_y_v1}"
TRAIN_META="${TRAIN_META:-}"
VAL_META="${VAL_META:-}"
TEST_META="${TEST_META:-}"
TRAIN_OUTPUT="$OUTPUT_ROOT/train/$METHOD_NAME/$TAG"
INFER_OUTPUT="$OUTPUT_ROOT/infer"
EVAL_OUTPUT="$OUTPUT_ROOT/eval/$METHOD_NAME/$TAG"
SWINFUSION_CKPT="${SWINFUSION_CKPT:-}"
SWINFUSION_CHECKPOINT_MODE="${SWINFUSION_CHECKPOINT_MODE:-metadata-y}"
INIT_MODE="${INIT_MODE:-scratch}"
INIT_CHECKPOINT_DIR="${INIT_CHECKPOINT_DIR:-}"
RESUME_DIR="${RESUME_DIR:-}"
NUM_WORKERS="${NUM_WORKERS:-4}"
MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-20000}"
VALIDATION_MODE="${VALIDATION_MODE:-loss}"
TRAIN_CROP_SIZE="${TRAIN_CROP_SIZE:-128}"
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-9}"

if [[ "$RUN_TRAIN" == 1 ]]; then
  require_file "$TRAIN_META" TRAIN_META
  require_file "$VAL_META" VAL_META
  METHOD=swinfusion TRAIN_META="$TRAIN_META" VAL_META="$VAL_META" OUTPUT_ROOT="$OUTPUT_ROOT/train" \
    TAG="$TAG" GPUS="$CUDA_VISIBLE_GPU" PYTHON="$PYTHON" INIT_MODE="$INIT_MODE" \
    INIT_CHECKPOINT_DIR="$INIT_CHECKPOINT_DIR" RESUME_DIR="$RESUME_DIR" NUM_WORKERS="$NUM_WORKERS" \
    MAX_SAMPLES="$MAX_SAMPLES" MAX_TRAIN_STEPS="$MAX_TRAIN_STEPS" SEED="$SEED" \
    TRAIN_CROP_SIZE="$TRAIN_CROP_SIZE" TRAIN_BATCH_SIZE="$TRAIN_BATCH_SIZE" \
    VALIDATION_MODE="$VALIDATION_MODE" bash "$ROOT/run_train_metadata_v3.sh"
fi

if [[ "$RUN_INFER" == 1 ]]; then
  if [[ -z "$SWINFUSION_CKPT" ]]; then
    SWINFUSION_CKPT="$(find "$TRAIN_OUTPUT/checkpoints" -maxdepth 1 -type f -name '*_E.pth' -printf '%f\n' 2>/dev/null | sort -n | tail -1 || true)"
    [[ -z "$SWINFUSION_CKPT" ]] || SWINFUSION_CKPT="$TRAIN_OUTPUT/checkpoints/$SWINFUSION_CKPT"
  fi
  require_file "$TEST_META" TEST_META
  require_file "$SWINFUSION_CKPT" SWINFUSION_CKPT
  METHOD=swinfusion METADATA="$TEST_META" OUTPUT_ROOT="$INFER_OUTPUT" PYTHON="$PYTHON" \
    SWINFUSION_CKPT="$SWINFUSION_CKPT" SWINFUSION_CHECKPOINT_MODE="$SWINFUSION_CHECKPOINT_MODE" \
    CUDA_VISIBLE_GPU="$CUDA_VISIBLE_GPU" SEED="$SEED" START_INDEX="$START_INDEX" \
    MAX_SAMPLES="$MAX_SAMPLES" OVERWRITE="$OVERWRITE" bash "$ROOT/run_infer_metadata_v3.sh"
fi

if [[ "$RUN_EVAL" == 1 ]]; then
  run_eval_for_specs "$METHOD_NAME" "$INFER_OUTPUT" "$EVAL_OUTPUT" "$EVAL_SPECS"
fi
